plugins {
    id 'java'
    id 'application'
    id 'java-library'
}

application {
    mainClass = 'org.foxesworld.kalitech.engine.KalitechLauncher'
}

repositories {
    mavenCentral()
    maven { url = uri("https://packages.jetbrains.team/maven/p/ij/intellij-dependencies/") }
    maven { url = uri("https://packages.jetbrains.team/maven/p/ij/intellij-dependencies/") } // JCEF
    maven { url = uri("https://jogamp.org/deployment/maven/") } // JOGL/GlueGen
}


dependencies {
    implementation project(':kalitech-core')
    implementation project(':kalitech-neural')

    implementation("com.github.ben-manes.caffeine:caffeine:3.2.3")

    api "org.jmonkeyengine:jme3-core:${rootProject.ext.jmeVersion}"
    api "org.jmonkeyengine:jme3-desktop:${rootProject.ext.jmeVersion}"
    api "org.jmonkeyengine:jme3-lwjgl3:${rootProject.ext.jmeVersion}"
    api "org.jmonkeyengine:jme3-plugins:${rootProject.ext.jmeVersion}"
    api "org.jmonkeyengine:jme3-effects:${rootProject.ext.jmeVersion}"

    implementation 'me.friwi:jcefmaven:141.0.10'
    implementation 'me.friwi:jcef-natives-windows-amd64:jcef-2caef5a+cef-141.0.10+g1d65b0d+chromium-141.0.7390.123'



    implementation "org.jmonkeyengine:jme3-plugins:${rootProject.ext.jmeVersion}"
    implementation "org.jmonkeyengine:jme3-jogg:${rootProject.ext.jmeVersion}"
    implementation "org.jmonkeyengine:jme3-awt-dialogs:${rootProject.ext.jmeVersion}"
    implementation 'com.github.stephengold:Minie:9.0.3'

    implementation "org.graalvm.polyglot:polyglot:${rootProject.ext.graalVersion}"
    implementation "org.graalvm.polyglot:js:${rootProject.ext.graalVersion}"

    //HUD
    implementation "com.simsilica:lemur:1.16.0"
    implementation "org.apache.groovy:groovy-jsr223:5.0.3"
}
