plugins {
    id 'java-library'
}

version = '1.0.0'

dependencies {
    implementation project(':kalitech-engine')
    implementation project(':kalitech-core')
    implementation "org.jmonkeyengine:jme3-jogg:${rootProject.ext.jmeVersion}"
}

tasks.named('jar') {
    archiveBaseName.set('SoundModule')
}
